### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by oblitum** [wokalski/Distraction-Free-Xcode-plugin#14]
Hi, by the title of the project it seems you're doing something I appreciate a lot =)

Sadly, I'm on last Xcode 7 Beta and I still didn't figure it out how to use the plugin. "GO ZEN" crashes, so I've uninstalled the Zen part and left only the main plugin but I'm not finding any button or menu to use it.

Thanks is advance.

**Comment by oblitum** [comment]
By the way, I've patched it locally with beta UUIDs for trying it.

**Comment by wokalski** [comment]
I'm going to work on that. This plugin is not finished yet; therefore it might crash. It was not even tested in Xcode 7. It's gonna be released soon for 6.x and a patch for Xcode 7 will follow it.

**Comment by oblitum** [comment]
OK thanks, I guess I will wait patiently for the release.

**Comment by wokalski** [comment]
I am open to all contributions of course. I had a little break from programming thus 1 month silence.
