### ISSUE TITLE
Possible UX Improvements

### ISSUE THREAD

**Issue by maartenschumacher** [wokalski/Distraction-Free-Xcode-plugin#15]
I was playing around with it and noticed some things:
- I at first thought that the disappearing white frame around the editor was a bug. Maybe it would be more clear that it's expected behavior if it fades in/out.
- Why doesn't the scroll bar go away as well? Its gray color disturbs my zen.
- How do I exit? My first thought was to go back to the view menu, where I activated zen mode. There was no "exit ZEN" option so I just pressed GO ZEN again. I guess this opened another window. Then I tried the red close button in the top left corner. The first time I didn't notice any change (because I accidentally opened a second window probably) and the second time it worked.
- Maybe the text font of the editor can become a bit bigger when we enter zen mode? Just to increase the feeling of "focusing in" on the code.

Great plugin overall! :)

**Comment by wokalski** [comment]
@maartenschumacher 
1. It is going to be adressed, definitely.
2. I think it does go away. It's normal that it appears on the screen during scrolling but it shouldn't be there anymore when you finished scrolling. If it's not the case for you please elaborate more!
3. This is not going to be adressed. You simply click red button. It's a standard Mac behaviour.
4. It is not possible easily. I wouldn't like it anyway. 

Thanks for the contribution!

**Comment by maartenschumacher** [comment]
@wczekalski 
1. This is what the scroll bar looks like for me :/ 
2. I forgot to say that actually the first thing I tried was pressing the "escape" key on my keyboard, which is how I usually exit some full screen mode. I didn't actually realize that it just opened another window.

![screen shot 2015-09-01 at 14 17 33](https://cloud.githubusercontent.com/assets/10407025/9603940/4b5491a6-50b4-11e5-83f4-998399f3403c.png)

**Comment by maartenschumacher** [comment]
Actually I tried pressing escape when I use the osx full-screen feature (the green button) and it didn't work either :)

But to be fair, pressing the red button doesn't return to normal size but gets rid of the entire window. I guess this is what actually should happen because the zen mode is just a window, but again, it wasn't clear to me that it worked like that.

**Comment by wokalski** [comment]
The animation was added in #17
