### ISSUE TITLE
Close distraction free window by clicking escape key

### ISSUE THREAD

**Issue by wokalski** [wokalski/Distraction-Free-Xcode-plugin#16]

**Comment by oblitum** [comment]
Wouldn't this enter in conflict with XVim plugin? A working ESC is a must for Vi mode.

**Comment by oblitum** [comment]
IMO, distraction free mode is more related to full-screen which commonly is related to F11, or a hotkey using it, although OS X apps generally use some cmd-anything for that.

**Comment by benkane** [comment]
CTRL + F11 is pretty typical for triggering a distraction free mode. I'd suggest that, personally.

**Comment by wokalski** [comment]
I didn't think too much when I created this issue; stupid. I am not sure if I'm gonna implement CTRL+F11 either. ZEN mode cannot be "minimized", it just can be closed. Therefore cmd+W, standard OS X shortcut should be used for that. 

Closing. Thank you guys for any contribution! The final release is going to be really really soon
