### ISSUE TITLE
Toggle back to normal mode?

### ISSUE THREAD

**Issue by RobertGummesson** [wokalski/Distraction-Free-Xcode-plugin#37]
I like the idea of this plugin but I couldn't find a way to leave the distraction free mode once I had entered it. How do I toggle back and forth?

Once in distraction free mode, I had to restart Xcode to get back to normal mode.

**Comment by wokalski** [comment]
Just do command+W to exit. It opens a new fullscreen window. You can exit from it the same as you would exit from Any other fullscreen window.

**Comment by RobertGummesson** [comment]
Ah, that worked. Thanks. (I never go fullscreen otherwise)

**Comment by gblazex** [comment]
Shouldn't this be more straightforward?

e.g. both the menu item & shortcut should do toggle ?
(trigger once goes into distraction free mode, next trigger reverts to standard mode)

cc @wczekalski

**Comment by benkane** [comment]
Completely agree, the same shortcut should act as a toggle. You are toggling a_mode_. It doesn't matter that behind the scenes it's a full screen window. The point is to turn a mode on/off. Every other editor ever that I can think of implements this as a toggle.

**Comment by wokalski** [comment]
You're right guys. I should've thought about it. I don't have time to implement it this weekend (_might_ do it on Sat) though. If any of you finds some time pull requests are welcome!

**Comment by thomasvalera** [comment]
+1

**Comment by wokalski** [comment]
:+1: fixed. It improves the UX indeed
