### ISSUE TITLE
Incompatible with Xcode 7

### ISSUE THREAD

**Issue by polandtyler** [wokalski/Distraction-Free-Xcode-plugin#41]
Via alcatraz install. 
Cannot select Distraction Free Mode via View Menu
![screen shot 2015-09-16 at 3 21 22 pm](https://cloud.githubusercontent.com/assets/3914742/9918860/a0518884-5c86-11e5-87c0-cc5dc883bb44.png)

**Comment by wokalski** [comment]
It works now! @polandtyler

**Comment by joelekstrom** [comment]
Hi. I have now gotten the same problem in Xcode 7.1.1

**Comment by wokalski** [comment]
@accatyyc fixed in #45

**Comment by hayek** [comment]
Hi. I have now gotten the same problem in Xcode 7.2
