### ISSUE TITLE
Incompatible with Xcode 7.2

### ISSUE THREAD

**Issue by niklasberglund** [wokalski/Distraction-Free-Xcode-plugin#48]
Same as https://github.com/wokalski/Distraction-Free-Xcode-plugin/issues/41 but with Xcode 7.2.

Can't select distraction free mode via view menu. Installed using Alcatraz.

**Comment by Paul-van-Klaveren** [comment]
#49 only makes the plug-in compatible with Xcode 7.2.1. It does not fix any other issues with the 7.2 line. In my case the plugin is now loaded, but crashes when I switch to distraction free mode — could of course be related to some other plug-in, not this one.

**Comment by wokalski** [comment]
As noted by @Paul-van-Klaveren it crashes when launched.

**Comment by jiashuw** [comment]
It crashes on clean installed Xcode 7.2.1 without any other plugins.

**Comment by fuxx** [comment]
Removing the observer like in the following commit makes the plugin work again.

**Comment by fuxx** [comment]
I've debugged the Plug-In a little bit. 
Removing the following lines like here makes the plugin working again. Unfortunately i have no idea what they are used for, but for me it works again. Maybe @wokalski can explain the need of them.

https://github.com/fuxx/Distraction-Free-Xcode-plugin/commit/79784fb95c723b4267a83d3278a9f9cca1a4075e

**Comment by wokalski** [comment]
I didn't realize that people use this plugin. I will resolve the issues you have this weekend. 
The lines that you have commented out were there to support the change of frame i.e. if the screen is changed. I will fix it. Thanks for your contribution. Appreciated.
