### ISSUE TITLE
Crash on Xcode 7.2.1 when try to enter this mode from view menu

### ISSUE THREAD

**Issue by yam-liu** [wokalski/Distraction-Free-Xcode-plugin#50]
Process:               Xcode [47706]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.2.1 (9548.1)
Build Info:            IDEFrameworks-9548001000000000~2
App Item ID:           497799835
App External ID:       816142004
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [47706]
User ID:               501

Date/Time:             2016-03-18 15:08:19.764 +0800
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        DB8DC263-4704-C677-5A3B-09E683D689A7

Sleep/Wake UUID:       F9241315-2BBD-4AD0-9667-C8FF56808071

Time Awake Since Boot: 810000 seconds
Time Since Wake:       4500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
ProductBuildVersion: 7C1002
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): An instance 0x7ff303b8ff60 of class NSNextStepFrame was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7ff2fd5112d0> (
<NSKeyValueObservance 0x7ff3032d1070: Observer: 0x7ff3021b48c0, Key path: frame, Options: <New: NO, Old: NO, Prior: YES> Context: 0x7ff2e4138a70, Property: 0x7ff3021b7e20>
)
UserInfo: (null)
Hints: None
Backtrace:
  0  0x00007fff92034aca **exceptionPreprocess (in CoreFoundation)
  1  0x000000010914cb07 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff837d6f7e objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff9203498d +[NSException raise:format:](in CoreFoundation)
  4  0x00007fff9436fecc NSKVODeallocate (in Foundation)
  5  0x00007fff8f7b2011 __25-[NSWindow setStyleMask:]_block_invoke (in AppKit)
  6  0x00007fff8fe2e659 NSPerformVisuallyAtomicChange (in AppKit)
  7  0x00007fff8f7b1e05 -[NSWindow setStyleMask:](in AppKit)
  8  0x00007fff8f9268ea -[NSWindow _didEnterFullScreen](in AppKit)
  9  0x00007fff8ff451ff __121-[_NSFullScreenTransition _doSucceededToEnterFullScreenWithAnimation:doKitAnimation:customWindows:duration:spid:subspid:]_block_invoke (in AppKit)
 10  0x00007fff91f7abc4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** (in CoreFoundation)
 11  0x00007fff91f7a853 __CFRunLoopDoTimer (in CoreFoundation)
 12  0x00007fff91ff8e6a __CFRunLoopDoTimers (in CoreFoundation)
 13  0x00007fff91f35cd1 __CFRunLoopRun (in CoreFoundation)
 14  0x00007fff91f35338 CFRunLoopRunSpecific (in CoreFoundation)
 15  0x00007fff8bf45935 RunCurrentEventLoopInMode (in HIToolbox)
 16  0x00007fff8bf4576f ReceiveNextEventCommon (in HIToolbox)
 17  0x00007fff8bf455af _BlockUntilNextEventMatchingListInModeWithFilter (in HIToolbox)
 18  0x00007fff8f6830ee _DPSNextEvent (in AppKit)
 19  0x00007fff8fa4f943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:](in AppKit)
 20  0x000000010972a0c2 -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:](in DVTKit)
 21  0x00007fff8f678fc8 -[NSApplication run](in AppKit)
 22  0x00007fff8f5fb520 NSApplicationMain (in AppKit)
 23  0x00007fff8bb065ad start (in libdyld.dylib)

abort() called

Application Specific Signatures:
An instance of class NSNextStepFrame was deallocated while key value observers were still registered with it. Key paths: (frame)

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff92034ae2 **exceptionPreprocess + 178
1   DVTFoundation                       0x000000010914cb07 DVTFailureHintExceptionPreprocessor + 194
2   libobjc.A.dylib                     0x00007fff837d6f7e objc_exception_throw + 48
3   CoreFoundation                      0x00007fff9203498d +[NSException raise:format:] + 205
4   Foundation                          0x00007fff9436fecc NSKVODeallocate + 294
5   AppKit                              0x00007fff8f7b2011 __25-[NSWindow setStyleMask:]_block_invoke + 397
6   AppKit                              0x00007fff8fe2e659 NSPerformVisuallyAtomicChange + 147
7   AppKit                              0x00007fff8f7b1e05 -[NSWindow setStyleMask:] + 222
8   AppKit                              0x00007fff8f9268ea -[NSWindow _didEnterFullScreen] + 49
9   AppKit                              0x00007fff8ff451ff __121-[_NSFullScreenTransition _doSucceededToEnterFullScreenWithAnimation:doKitAnimation:customWindows:duration:spid:subspid:]_block_invoke + 115
10  CoreFoundation                      0x00007fff91f7abc4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 20
11  CoreFoundation                      0x00007fff91f7a853 __CFRunLoopDoTimer + 1075
12  CoreFoundation                      0x00007fff91ff8e6a __CFRunLoopDoTimers + 298
13  CoreFoundation                      0x00007fff91f35cd1 __CFRunLoopRun + 1841
14  CoreFoundation                      0x00007fff91f35338 CFRunLoopRunSpecific + 296
15  HIToolbox                           0x00007fff8bf45935 RunCurrentEventLoopInMode + 235
16  HIToolbox                           0x00007fff8bf4576f ReceiveNextEventCommon + 432
17  HIToolbox                           0x00007fff8bf455af _BlockUntilNextEventMatchingListInModeWithFilter + 71
18  AppKit                              0x00007fff8f6830ee _DPSNextEvent + 1067
19  AppKit                              0x00007fff8fa4f943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
20  DVTKit                              0x000000010972a0c2 -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 247
21  AppKit                              0x00007fff8f678fc8 -[NSApplication run] + 682
22  AppKit                              0x00007fff8f5fb520 NSApplicationMain + 1176
23  libdyld.dylib                       0x00007fff8bb065ad start + 1

Global Trace Buffer (reverse chronological seconds):
22.823051    CFNetwork                  0x00007fff8c259a5b TCP Conn 0x7ff2f64a4240 SSL Handshake DONE
24.005503    CFNetwork                  0x00007fff8c259937 TCP Conn 0x7ff2f64a4240 starting SSL negotiation
24.317013    CFNetwork                  0x00007fff8c258303 TCP Conn 0x7ff2f64a4240 complete. fd: 49, err: 0
24.318632    CFNetwork                  0x00007fff8c2e6b1d TCP Conn 0x7ff2f64a4240 event 1. err: 0
24.331113    CFNetwork                  0x00007fff8c2575d3 TCP Conn 0x7ff2f64a4240 started
24.388649    CFNetwork                  0x00007fff8c21b21a Creating default cookie storage with process/bundle identifier
24.388649    CFNetwork                  0x00007fff8c21b1b2 Faulting in CFHTTPCookieStorage singleton
24.388660    CFNetwork                  0x00007fff8c21b041 Faulting in NSHTTPCookieStorage singleton
24.433270    CFNetwork                  0x00007fff8c318654 NSURLConnection finished with error - code -1100

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff91e90002 __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff9942c5c5 pthread_kill + 90
2   libsystem_c.dylib               0x00007fff8df756e7 abort + 129
3   com.apple.dt.IDEKit             0x000000010a5c4981 +[IDEAssertionHandler _handleAssertionWithLogString:assertionSignature:assertionReason:extraBacktrace:] + 1481
4   com.apple.dt.IDEKit             0x000000010a5c5c1a -[IDEAssertionHandler handleUncaughtException:] + 1077
5   com.apple.dt.IDEKit             0x000000010a5c5ce6 IDEHandleUncaughtException + 94
6   com.apple.AppKit                0x00007fff8f6790de -[NSApplication run] + 960
7   com.apple.AppKit                0x00007fff8f5fb520 NSApplicationMain + 1176
8   libdyld.dylib                   0x00007fff8bb065ad start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff91e90ff6 kevent_qos + 10
1   libdispatch.dylib               0x00007fff91c7e099 _dispatch_mgr_invoke + 216
2   libdispatch.dylib               0x00007fff91c7dd01 _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib          0x00007fff91e8a386 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff91e897c7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91f36624 **CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91f35aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91f35338 CFRunLoopRunSpecific + 296
5   com.apple.Foundation            0x00007fff94357e61 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270
6   com.apple.DTDeviceKitBase       0x00000001120365e0 -[DTDKRemoteDeviceDataListener listenerThreadImplementation] + 1103
7   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
8   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
9   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
10  libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 7:: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x00007fff91e90176 __select + 10
1   com.apple.CoreFoundation        0x00007fff91f8216a __CFSocketManager + 762
2   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
3   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
4   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 8:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x00007fff91e8a386 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff91e897c7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91f36624 **CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91f35aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91f35338 CFRunLoopRunSpecific + 296
5   com.apple.CFNetwork             0x00007fff8c21e6e9 +[NSURLConnection(Loader) _resourceLoadLoop:] + 412
6   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
7   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
8   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
9   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 10:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 11:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 12:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 13:: com.apple.NSEventThread
0   libsystem_kernel.dylib          0x00007fff91e8a386 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff91e897c7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91f36624 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91f35aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91f35338 CFRunLoopRunSpecific + 296
5   com.apple.AppKit                0x00007fff8f742065 _NSEventThread + 149
6   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
8   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 14:: DYMobileDeviceManager
0   libsystem_kernel.dylib          0x00007fff91e8a386 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff91e897c7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91f36624 **CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91f35aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91f35338 CFRunLoopRunSpecific + 296
5   com.apple.Foundation            0x00007fff94357e61 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270
6   com.apple.Foundation            0x00007fff943c9afd -[NSRunLoop(NSRunLoop) run] + 74
7   com.apple.GPUToolsMobileFoundation  0x000000011d7e4071 -[DYMobileDeviceManager _deviceNotificationThread:] + 134
8   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
9   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
10  libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
11  libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 15:
0   libsystem_kernel.dylib          0x00007fff91e8feb2 **psynch_cvwait + 10
1   libsystem_pthread.dylib         0x00007fff9942b150 _pthread_cond_wait + 767
2   com.apple.Xcode.DevToolsCore    0x0000000111b0550b -[XCBlockQueue _processBlocksInThreadSlotNumber:] + 450
3   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
4   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
5   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
6   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 16:
0   libsystem_kernel.dylib          0x00007fff91e8feb2 **psynch_cvwait + 10
1   libsystem_pthread.dylib         0x00007fff9942b150 _pthread_cond_wait + 767
2   com.apple.Xcode.DevToolsCore    0x0000000111b0550b -[XCBlockQueue _processBlocksInThreadSlotNumber:] + 450
3   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
4   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
5   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
6   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 17:
0   libsystem_kernel.dylib          0x00007fff91e8feb2 **psynch_cvwait + 10
1   libsystem_pthread.dylib         0x00007fff9942b150 _pthread_cond_wait + 767
2   com.apple.Xcode.DevToolsCore    0x0000000111b0550b -[XCBlockQueue _processBlocksInThreadSlotNumber:] + 450
3   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
4   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
5   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
6   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 18:
0   libsystem_kernel.dylib          0x00007fff91e8feb2 **psynch_cvwait + 10
1   libsystem_pthread.dylib         0x00007fff9942b150 _pthread_cond_wait + 767
2   com.apple.Xcode.DevToolsCore    0x0000000111b0550b -[XCBlockQueue _processBlocksInThreadSlotNumber:] + 450
3   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
4   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
5   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
6   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 19:
0   libsystem_kernel.dylib          0x00007fff91e8feb2 **psynch_cvwait + 10
1   libsystem_pthread.dylib         0x00007fff9942b150 _pthread_cond_wait + 767
2   com.apple.Xcode.DevToolsCore    0x0000000111b0550b -[XCBlockQueue _processBlocksInThreadSlotNumber:] + 450
3   com.apple.Foundation            0x00007fff944a3c6f __NSThread__start** + 1351
4   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
5   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
6   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 20:
0   libsystem_kernel.dylib          0x00007fff91e906de __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff9942a729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff99428365 start_wqthread + 13

Thread 21:

Thread 22:
0   libsystem_kernel.dylib          0x00007fff91e8a386 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff91e897c7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91f36624 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91f35aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91f35338 CFRunLoopRunSpecific + 296
5   com.apple.CoreFoundation        0x00007fff91ff81f1 CFRunLoopRun + 97
6   com.apple.DebugSymbols          0x00007fff931fe69a SpotlightQueryThread(void*) + 346
7   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
8   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
9   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 23:
0   libsystem_kernel.dylib          0x00007fff91e90206 __semwait_signal + 10
1   libsystem_c.dylib               0x00007fff8df96d17 nanosleep + 199
2   com.apple.CoreSymbolication     0x00007fff952cdb5f 0x7fff952bb000 + 76639
3   libsystem_pthread.dylib         0x00007fff9942ac13 _pthread_body + 131
4   libsystem_pthread.dylib         0x00007fff9942ab90 _pthread_start + 168
5   libsystem_pthread.dylib         0x00007fff99428375 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff56cefa18  rdx: 0x0000000000000000
  rdi: 0x000000000000160b  rsi: 0x0000000000000006  rbp: 0x00007fff56cefa40  rsp: 0x00007fff56cefa18
   r8: 0x00007ff2e3f3d032   r9: 0x0000000000000000  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff837ce0e0  r13: 0x00007ff301811610  r14: 0x00007fff77381000  r15: 0x00007ff2f3c17400
  rip: 0x00007fff91e90002  rfl: 0x0000000000000206  cr2: 0x00007fff74e80008

Logical CPU:     0
Error Code:      0x020000b8
Trap Number:     133

**Comment by wokalski** [comment]
Duplicate of #48
