### ISSUE TITLE
Please add Xcode 7.3 compability.

### ISSUE THREAD

**Issue by ghost** [wokalski/Distraction-Free-Xcode-plugin#52]

**Comment by jonchoi** [comment]
+1

**Comment by wokalski** [comment]
I will look into it.

**Comment by wokalski** [comment]
I have spent some time this weekend to debug it and Xcode had some internals refactored around editor. However, the change looks pretty small and I will update it soon once I make it fully work (there are still some cases when the editor doesn't open files).

**Comment by huangxiangdan** [comment]
hi, @wokalski , is everything going well? I'm expecting this plugin work with xcode 7.3 very much.

**Comment by wokalski** [comment]
no, not exactly. The scope of this issue is behind of what I can do now - i don't quite have time. Basically Xcode was refactored and there are some bits and pieces to change.

**Comment by wokalski** [comment]
I decided to stop maintaining this plugin. Why? I don't like Xcode and I use other tools now. Any contributions are welcome though.
